name: Publish pymkv to PyPI and Test PyPI
on:
  push:
    tags:
      - 'v*'
jobs:
  build-n-publish:
    name: Publish pymkv to PyPI and Test PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install and upgrade build tool packages
      run: |
        pip install --upgrade setuptools twine wheel
    - name: Build source and wheel
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_PASSWORD }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
